### ISSUE TITLE
text overflow should be resolved

### ISSUE THREAD

**Issue by Himika-Mishra** [DhairyaBahl/React-Messenger-App#90]
Hi @DhairyaBahl ,

I have seen that the text overflow has not been resolved until now.

Please assign this task to me so that I start working on it. @DhairyaBahl Please assign it to me.

I will resolve it ASAP.

Thanks
Himika Mishra

**Comment by DhairyaBahl** [comment]
@Himika-Mishra I think it is resolved ! Do confirm it once and if you can send some SS to confirm that then that will be pretty awesome. This is because PR for the same was merged today morning.

**Comment by Himika-Mishra** [comment]
Okay yaa sure.

**Comment by Himika-Mishra** [comment]
Hi Dhairya,

I have just reviewed the site once more and I have found that the text
overflow was not resolved.
I am providing you with an ss.

Please assign me this task and I will sort it out today itself.

Thanks
Himika Mishra

**Comment by Himika-Mishra** [comment]
Hi @DhairyaBahl,
Please see the above message.

Thanks
Himika Mishra

**Comment by abhijeet007rocks8** [comment]
Go Ahead @Himika-Mishra 
During PR  do submit the before after screenshot it helps us to review.

**Comment by Himika-Mishra** [comment]
Okay I will do this.

Thanx a lot

**Comment by AnjaliPatle** [comment]
Hey @abhijeet007rocks8  and @Himika-Mishra . I was assigned the issue to resolve text-overflow previously and I made the required changes. However I think that the contributor for PR #87 commented the previous styles and added new styles without accounting for updates in the previous css code. Please look into it and I think that should resolve this issue!

**Comment by abhijeet007rocks8** [comment]
Thank You for bringing this to our notice. We will see to the issue.

**Comment by abhijeet007rocks8** [comment]
@Himika-Mishra can you send the screenshots??

**Comment by DhairyaBahl** [comment]
@abhijeet007rocks8 @Himika-Mishra This issue is already resolved ! I have deployed all the changes. You can checkout on the website. Thanks for cooperation.
